### ISSUE TITLE
core/stencils/themes/default : Menu design in Illstrator

### ISSUE THREAD

**Issue by mattmoriarty** [stencila/tickets#11]
This ticket is for overall menu design for the stencil menu in the default theme. A place to play around with general ideas of what will go in the menu and how it might look.

- informational section (describing current state of stencil)
  - stencil address (? is this needed, already in URL)
  - active/deactivate taggle
  - owner
  - public/private flag
  - number of views
  - number of stars
- views sections
  - normal
  - reveal
  - edit
  - html
  - cila
- actions section
  - save
  - refresh (partial re-rendering of stencil; only directives that have changed are rendered)
  - restart (full re-rendering of stencil)
- share section
  - publish stencil (make it available to world, or to selected users)
  - facebook
  - twitter
  - (etc)
- export section
 - word
 - pdf
 - (others?)

**Comment by nokome** [comment]
Hey @mattmoriarty, just edited the title & description of this. Why don't we make this ticket a scratch pad for general menu design (counter to what I said earlier, I know). Keep, an easy to edit nested list of items in the ticket description along with any mockups.

**Comment by mattmoriarty** [comment]
Here is a first dig at the menu.
My thoughts;
1. Do we need icons for everything? Perhaps a list is simpler and keeps the hierarchy with more important aspects?
2. Compressed view may be useful if the menu grows beyond standard screen height or using in smaller devices. See image below (left column).
3. White Active / Grey non active state.

![screen shot 2015-04-16 at 3 34 24 pm](https://cloud.githubusercontent.com/assets/11878224/7173629/c6bdcc86-e44e-11e4-89a7-69b791636c31.png)

**Comment by mattmoriarty** [comment]
Rev 150507 based on discussion last week;

![150507 homepage design in illustrator-02](https://cloud.githubusercontent.com/assets/11878224/7508812/273540b6-f4db-11e4-8e17-a5453a040191.png)

**Comment by nokome** [comment]
Implement some of the above menu items as "coming", then close this ticket.
