### ISSUE TITLE
core/stencils/index : design

### ISSUE THREAD

**Issue by mattmoriarty** [stencila/tickets#12]

**Comment by mattmoriarty** [comment]
Will start playing with home page layout in Illustrator.
Ideas discussed so far;
- Title / owner / brief description. 
- Thumbnail image preview of doc.
-  Views / Likes / Privacy preview.
- Three column approach (changes to one or two column depending on device)

**Comment by mattmoriarty** [comment]
Homepage: Idea for side menu / login / chat icons; Icons becomes more visible (less transparent) as mouse gets closer. Could be a nice way to maintain a minimal homepage feel?

**Comment by mattmoriarty** [comment]
First rough cut of look & feel;
![screen shot 2015-04-16 at 5 19 34 pm](https://cloud.githubusercontent.com/assets/11878224/7174493/580debe0-e45d-11e4-9469-4b5f8a137713.png)

**Comment by nokome** [comment]
Looking great! Some articles that are probably of use for CSS implementation:

- http://demosthenes.info/blog/825/Pinterest-Style-Layout-In-Pure-CSS
- http://demosthenes.info/blog/532/Convert-Images-To-Black-And-White-With-CSS

**Comment by mattmoriarty** [comment]
Rev 150507 visually implementing discussion points;

![150507 homepage design in illustrator-01](https://cloud.githubusercontent.com/assets/11878224/7508778/9f55baae-f4da-11e4-8bfa-eca12bbd99f6.png)

![150507 homepage design in illustrator-02](https://cloud.githubusercontent.com/assets/11878224/7508781/afca6b6e-f4da-11e4-89ee-72e16a7e091c.png)

**Comment by mattmoriarty** [comment]
Header: Logo and Logotype | Documents Powered by Data.

**Comment by mattmoriarty** [comment]
Footer: 
US | About Contact Blog?
& YOU | Community Blog?

**Comment by nokome** [comment]
I have bunged a logo on this page but at this stage, until #20 is tackled, I don't think the footer elements should be attempted. So, closing this ticket.
