### ISSUE TITLE
core/themes/base : typography

### ISSUE THREAD

**Issue by nokome** [stencila/tickets#15]
Define font details for base theme. Worthwhile reminding ourselves of the definition of the word (Wikipedia):

> Typography is the art and technique of arranging type to make written language readable and
> appealing. The arrangement of type involves selecting typefaces, point size, line length, line-spacing
> (leading), letter-spacing (tracking), and adjusting the space within letters pairs (kerning).

Current font definitions follow. Should just need these four:

Serif font stack for stencil text:
```css
font-family: Perpetua, Baskerville, "Big Caslon", "Palatino Linotype", Palatino, "URW Palladio L", "Nimbus Roman No9 L", serif;
```

Sans serif font stack for stencil headers, table and figure captions:
```css
font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
```

Sans serif font stack for menu items:
```css
font-family: 'Varela Round', 'Helvetica', sans-serif;
```

Monspace font stack for code:
```css
font-family: monospace;
```

See Skeleton's brief description of it's typography http://getskeleton.com/. Similar description to go in `core/docs/themes/base`

**Comment by mattmoriarty** [comment]
Note: Monospace: Andale Mono used on business cards

**Comment by nokome** [comment]
http://www.webdesignerdepot.com/2014/03/the-best-way-to-serve-fonts-to-your-website/

**Comment by nokome** [comment]
Currently using 'Source Code Pro' for mono but feels too wide.

**Comment by nokome** [comment]
We're done with for now, so I'm closing this!
