### ISSUE TITLE
core/themes/base : Icon set

### ISSUE THREAD

**Issue by nokome** [stencila/tickets#16]
Establish icon set. Use the  workflow described [here](http://danburzo.ro/svg-icon-system/) (uses Adobe Illustrator and Grunt).

**Comment by nokome** [comment]
@mattmoriarty, could you take this through to "Clean up and package the icons", then I can take over and set up the rest of the system.

**Comment by mattmoriarty** [comment]
HSB Colour Management: 

All icon colours are based on the saturation and brightness of Stencila Green and change in hue value only; Stencila Green has a saturation of 73% and brightness 90%.

The H values are as follows:
- Stencila Green 93
- Community Pink 319
- Organisation Blue 194

- New Orange 37
- New Yellow 55
- New Royal 224
- New Red 357

**Comment by nokome** [comment]
Started  a new `colors.scss` file to implement these as standards. To be finished and tested.

**Comment by nokome** [comment]
Commited with some minor changes. But not currently used.
