### ISSUE TITLE
core/stencils/themes/default : menu : activate Icon toggle colour state

### ISSUE THREAD

**Issue by mattmoriarty** [stencila/tickets#9]
Vertical deactivate, horizontal activate Red Green?

![screen shot 2015-04-10 at 12 26 40 pm](https://cloud.githubusercontent.com/assets/11878224/7079815/1c85b74a-df7d-11e4-8d26-3c1f5cb0e50d.png)

**Comment by mattmoriarty** [comment]
refer to core/stencils/themes/default : Menu design in Illustrator

**Comment by nokome** [comment]
Closing as duplicated in #11
